services:
  atlas-shell:
    container_name: atlas-shell
    build:
      context: ../..
      dockerfile: 02_Platform/Atlas_Shell/Dockerfile
    restart: unless-stopped
    ports:
      - "0.0.0.0:80:80"
    networks:
      - atlas-net

networks:
  atlas-net:
    external: true
